// 시스템 예외 코드
export const RAMS_ERROR_CODES = {
	MQTT_CREATE_ERROR: 'SYS_EXCEPT_0001',
	MQTT_PUBLISH_ERROR: 'SYS_EXCEPT_0002',
	GQL_CREATE_ERROR: 'SYS_EXCEPT_0003',
	GQL_REQUEST_ERROR: 'SYS_EXCEPT_0004',
	GQL_WS_CREATE_ERROR: 'SYS_EXCEPT_0005',
	GQL_SUBSCRIBE_ERROR: 'SYS_EXCEPT_0006',

	INVALID_INPUT_ERROR: 'APP_EXCEPT_0001',
	FAIL_LOGIN_ERROR: 'APP_EXCEPT_0002'
};
